var age = 25; // Number
var name = "John"; // String
var developer = true; // Boolean
var task; // undefined

let age1 = 25; // Number
let name1 = "John"; // String
let developer1 = true; // Boolean
let task1; // undefined
age1 = 50; // you can change variables which are made by using "let"
console.log(age1);

const age2 = 20;
const job = 'developer';
const name2 = 2;
const num = 10;
// num = 20; //Compiler Error: Cannot assign to 'num' because it is a constant or read-only property